version: '2'
services:

  webapp:
    build:
      context: ./webapp
    #image: webapp
    environment:
    - MONGO_PASSWORD="user"
    - MONGO_DB_USER="user"
    ports:
    - "3000"

  storage:
    container_name: storage
    build: ./mongodb
    #image: storage
    env_file:
      - ./mongo_config.env
    restart: always
    ports:
      - "27017"
  image: dockersamples/visualizer:stable
  ports:
  - "8080:8080"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
  placement:
  constraints: [node.role == manager]
  networks:
  - overlay
